### ISSUE TITLE
Update for version 0.14.0

### ISSUE THREAD

**Issue by Chumper** [everpeace/constructr-redis#4]
With version 0.14.0 this extension is not able to be instantiated anymore. 
My guess is that the constructor should be adjusted so that the prefix is not needed anymore.

```code
[ERROR] [11/04/2016 12:30:56.936] [my-app-akka.actor.default-dispatcher-18] [akka://my-app-akka/user/$a] A Coordination implementation must provide a constructor with the following signature:
(clusterName: String, system: ActorSystem)
akka.actor.ActorInitializationException: akka://my-app/user/$a: exception during creation
	at akka.actor.ActorInitializationException$.apply(Actor.scala:174)
	at akka.actor.ActorCell.create(ActorCell.scala:607)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:461)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:483)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
	at akka.dispatch.Mailbox.run(Mailbox.scala:223)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.Exception: A Coordination implementation must provide a constructor with the following signature:
(clusterName: String, system: ActorSystem)
	at de.heikoseeberger.constructr.coordination.Coordination$.apply(Coordination.scala:37)
	at de.heikoseeberger.constructr.Constructr.createConstructrMachine(Constructr.scala:91)
	at de.heikoseeberger.constructr.Constructr.<init>(Constructr.scala:61)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at akka.util.Reflect$.instantiate(Reflect.scala:44)
	at akka.actor.NoArgsReflectConstructor.produce(IndirectActorProducer.scala:105)
	at akka.actor.Props.newActor(Props.scala:213)
	at akka.actor.ActorCell.newActor(ActorCell.scala:562)
	at akka.actor.ActorCell.create(ActorCell.scala:588)
	... 9 more
```

**Comment by RomanIakovlev** [comment]
I've submitted a PR #6 that updates this project to current version (0.17.0) of ConstructR. @everpeace could you please have a look?
It's actually more than just removing a prefix from constructor. ConstructR API has changed significantly from 0.13.2 to 0.17.0, but my PR takes care of that.
